<script lang="ts">
  import { onMount } from "svelte";
  import { auth, getCurrentRole } from "../services/SessionStore";
  import InfoBlocks from "./InfoBlocks.svelte";
  import Charts from "./Charts.svelte";
  import Login from "../auth/Login.svelte";

  document.title = "Pegasus";

  type Item = {
    title: string;
    description: string;
    icon: string;
    emoji: string;
    href: string;
    color: string;
    admin: boolean;
    customer: boolean;
    default: boolean;
    id: number;
  };

  const allItems: Item[] = [
    
    {
      id: 1,
      emoji: "🍔",
      title: "Jelovnik",
      description: "Pregledaj proizvode",
      icon: "box--",
      href: "/products?listView=false",
      color: "green",
      default: true,
      admin: true,
      customer: true,
    },
    {
      id: 6,
      emoji: "🪑",
      title: "Stolovi",
      description: "Pregled i upravljanje stolovima",
      icon: "--table",
      href: "/tables",
      color: "yellow",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 2,
      emoji: "🥩",
      title: "Artikli",
      description: "Upravljanje artiklima",
      icon: "box--",
      href: "/artikli",
      color: "yellow",
      default: false,
      admin: true,
      customer: false,
    },
    {
      id: 3,
      emoji: "🧺",
      title: "Košarica",
      description: "Pregledaj proizvode u košarici",
      icon: "", //"shopping-basket",
      href: "/cart",
      color: "orange",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 4,
      emoji: "📝",
      title: "Narudžbe",
      description: "Pregled i upravljanje narudžbama",
      icon: "truck--",
      href: "/orders",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 5,
      emoji: "📅",
      title: "Rezervacije",
      description: "Upravljanje rezervacijama",
      icon: "truck--",
      href: "/reservations",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 0,
      emoji: "👤",
      title: "Korisnici",
      description: "Upravljanje korisnicima",
      icon: "users--",
      href: "/users",
      color: "blue",
      default: false,
      admin: true,
      customer: false,
    },
    {
      id: 7,
      emoji: "🖼️",
      title: "Galerija",
      description: "Pregled i upravljanje galerijom slika. Milijarde besplatnih slika putem Unsplash API",
      icon: "//image",
      href: "/pix",
      color: "violet",
      default: true,
      admin: true,
      customer: true,
    },
  ];

  const role = getCurrentRole();

  const getItemsByRole = (role: "ADMIN" | "CUSTOMER" | "EMPLOYEE"): Item[] => {
    return allItems.filter((route) => {
      if (route.default) return true;

      if (role === "ADMIN" || role === "EMPLOYEE") return route.admin === true;
      if (role === "CUSTOMER") return route.customer === true;

      return false;
    });
  };

  let items = getItemsByRole(role);

  async function addItemsWithDelay(
    sourceItems: Item[],
    addFn: (item: Item) => void,
    delay = 0 //za sad bez ovoga
  ) {
    for (const item of sourceItems) {
      addFn(item);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  let displayedItems: Item[] = [];

  onMount(() => {
    addItemsWithDelay(
      items,
      (item) => (displayedItems = [...displayedItems, item])
    );
  });

</script>
      
{#if !$auth.isAuthenticated}

  <Login />

{:else}
<div
  class="max-w-9xl mx-auto px-6 sm:pt-0
  grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-1 menu-container"
>
  {#each displayedItems as item}

    <a
      href="#{item.href}"
      class=""
    >
   <div class="menu-card card-8 ">
            <div class="card-content hover:bg-primary/20 flex flex-col items-center justify-center">
                <span class="icon">{item.emoji}</span>
                 <h2 class="title text-primary/60 ">{item.title}</h2>
            </div>
            <span class="arrow">→</span>
        </div>
    </a>

  {/each}
</div>

{/if}

<style>
  @keyframes wave {
    0%,
    100% {
      transform: translateX(0);
    }
    50% {
      transform: translateX(-50px);
    }
  }
  @keyframes slide {
    0% {
      transform: translateX(-20px) translateY(-20px);
    }
    100% {
      transform: translateX(20px) translateY(20px);
    }
  }

  @keyframes float {
    0%,
    100% {
      transform: translate(0, 0) scale(1);
    }
    33% {
      transform: translate(30px, -20px) scale(1.1);
    }
    66% {
      transform: translate(-20px, 30px) scale(0.9);
    }
  }
  /*********************************/
  /* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:00
* animation scale-up-center-normal
* ----------------------------------------
*/
  @keyframes scale-up-center-normal {
    0% {
      transform: scale(0.5);
    }
    100% {
      transform: scale(1);
    }
  }
  .scale-up-center-normal {
    animation: scale-up-center-normal 0.25s ease-out 0s 1 normal both;
  }
 

 .menu-container {
            display: grid;
            grid-template-columns: revert-layer !important;
            gap: 20px; 
            max-width: 1200px;
            width: 100%;
        }

        .menu-card {
            background: var(--color-base-200);
            backdrop-filter: blur(10px); 
            min-width: none; 
            position: relative;
            overflow: hidden;
            cursor: pointer;
            transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            height: -webkit-fill-available;
            align-content: center;
        }

        .menu-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
/*             background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
 */            opacity: 0;
/*             transition: opacity 0.4s ease;
 */            z-index: 0;
        }


        .menu-card:hover::before {
            opacity: 1;
        }

        .card-content {
            position: relative;
            z-index: 1;
 }

        .menu-card:hover .card-content
        {
            color: /*var(--color-primary)*/black;
        }

        .icon {
            font-size: 48px;
            margin-bottom: 20px;
         }


        .title {
            font-size: 24px;
            font-weight: 600;
            margin-bottom: 10px;
            letter-spacing: -0.5px;
        }

    

        .arrow {
            position: absolute;
            bottom: 20px;
            right: 20px;
            font-size: 24px;
            opacity: 0;
            transform: translateX(-10px);
            transition: all 0.4s ease;
        }

        .menu-card:hover .arrow {
            opacity: 1;
            transform: translateX(0);
        }



        @media (max-width: 768px) {
            .menu-container {
                grid-template-columns: 1fr;
            }
        }


</style>
