<script lang="ts">
  import { onMount } from "svelte";
  import { getCurrentRole } from "../services/SessionStore";
  import InfoBlocks from "./InfoBlocks.svelte";
  import Charts from "./Charts.svelte";

  document.title = "Pegasus";

  type Item = {
    title: string;
    description: string;
    icon: string;
    emoji: string;
    href: string;
    color: string;
    admin: boolean;
    customer: boolean;
    default: boolean;
    id: number;
  };

  const allItems: Item[] = [
    
    {
      id: 1,
      emoji: "🍔",
      title: "Jelovnik",
      description: "Pregledaj proizvode",
      icon: "box--",
      href: "/products?listView=false",
      color: "green",
      default: true,
      admin: true,
      customer: true,
    },
    {
      id: 6,
      emoji: "🪑",
      title: "Stolovi",
      description: "Pregled i upravljanje stolovima",
      icon: "--table",
      href: "/tables",
      color: "yellow",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 2,
      emoji: "🥩",
      title: "Artikli",
      description: "Upravljanje artiklima",
      icon: "box--",
      href: "/artikli",
      color: "yellow",
      default: false,
      admin: true,
      customer: false,
    },
    {
      id: 3,
      emoji: "🧺",
      title: "Košarica",
      description: "Pregledaj proizvode u košarici",
      icon: "", //"shopping-basket",
      href: "/cart",
      color: "orange",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 4,
      emoji: "📝",
      title: "Narudžbe",
      description: "Pregled i upravljanje narudžbama",
      icon: "truck--",
      href: "/orders",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 5,
      emoji: "📅",
      title: "Rezervacije",
      description: "Upravljanje rezervacijama",
      icon: "truck--",
      href: "/reservations",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 0,
      emoji: "👤",
      title: "Korisnici",
      description: "Upravljanje korisnicima",
      icon: "users--",
      href: "/users",
      color: "blue",
      default: false,
      admin: true,
      customer: false,
    },
    {
      id: 7,
      emoji: "🖼️",
      title: "Galerija",
      description: "Pregled i upravljanje galerijom slika. Milijarde besplatnih slika putem Unsplash API",
      icon: "//image",
      href: "/pix",
      color: "violet",
      default: true,
      admin: true,
      customer: true,
    },
  ];

  const role = getCurrentRole();

  const getItemsByRole = (role: "ADMIN" | "CUSTOMER" | "EMPLOYEE"): Item[] => {
    return allItems.filter((route) => {
      if (route.default) return true;

      if (role === "ADMIN" || role === "EMPLOYEE") return route.admin === true;
      if (role === "CUSTOMER") return route.customer === true;

      return false;
    });
  };

  let items = getItemsByRole(role);

  async function addItemsWithDelay(
    sourceItems: Item[],
    addFn: (item: Item) => void,
    delay = 60
  ) {
    for (const item of sourceItems) {
      addFn(item);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  let displayedItems: Item[] = [];

  onMount(() => {
    addItemsWithDelay(
      items,
      (item) => (displayedItems = [...displayedItems, item])
    );
  });

</script>
      
<!-- <InfoBlocks/>
 -->
<!-- <Charts/> -->

<div
  class="max-w-9xl mx-auto px-6 py-10
  grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 scale-up-center-normal menu-container"
>
  {#each displayedItems as item}


    <a
      href="#{item.href}"
      class=""
    >
   <div class="menu-card card-8">
            <div class="card-content">
                <span class="icon">{item.emoji}</span>
                 <h2 class="title">{item.title}</h2>
<!--                 <p class="description"> {item.description}</p>
 -->            </div>
            <span class="arrow">→</span>
        </div>
    </a>


  {/each}
</div>

<style>
  @keyframes wave {
    0%,
    100% {
      transform: translateX(0);
    }
    50% {
      transform: translateX(-50px);
    }
  }
  @keyframes slide {
    0% {
      transform: translateX(-20px) translateY(-20px);
    }
    100% {
      transform: translateX(20px) translateY(20px);
    }
  }

  @keyframes float {
    0%,
    100% {
      transform: translate(0, 0) scale(1);
    }
    33% {
      transform: translate(30px, -20px) scale(1.1);
    }
    66% {
      transform: translate(-20px, 30px) scale(0.9);
    }
  }
  /*********************************/
  /* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:00
* animation scale-up-center-normal
* ----------------------------------------
*/
  @keyframes scale-up-center-normal {
    0% {
      transform: scale(0.5);
    }
    100% {
      transform: scale(1);
    }
  }
  .scale-up-center-normal {
    animation: scale-up-center-normal 0.25s ease-out 0s 1 normal both;
  }
  .menu-block {
    display: inline-block; /* needed for transform to work properly */
    transition: transform 0.2s ease;
  }
  .menu-block:hover {
    transform: scale(2.1); /* 10% bigger */
  }
  .gblock {
    background-color: #003153 !important;
    background-image: linear-gradient(315deg, #062840 0%, #000 74%) !important;
  }

  /* From Uiverse.io by ElSombrero2 */ 
.card {
  width: 190px;
  height: 254px;
  background: #171717;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  position: relative;
  box-shadow: 0px 0px 3px 1px #00000088;
  cursor: pointer;
}

.card .content {
  border-radius: 5px;
  background: #171717;
  width: 186px;
  height: 250px;
  z-index: 1;
  padding: 20px;
  color: white;
  display: flex;
  justify-content: center;
  align-items: center;
}

.content::before {
  opacity: 0;
  transition: opacity 300ms;
  content: " ";
  display: block;
  background: white;
  width: 5px;
  height: 50px;
  position: absolute;
  filter: blur(50px);
  overflow: hidden;
}

.card:hover .content::before {
  opacity: 1;
}

.card::before {
  opacity: 0;
  content: " ";
  position: absolute;
  display: block;
  width: 80px;
  height: 360px;
  background: linear-gradient(#ff2288, #387ef0);
  transition: opacity 300ms;
  animation: rotation_9018 8000ms infinite linear;
  animation-play-state: paused;
}

.card:hover::before {
  opacity: 1;
  animation-play-state: running;
}

.card::after {
  position: absolute;
  content: " ";
  display: block;
  width: 250px;
  height: 360px;
  background: #17171733;
  backdrop-filter: blur(50px);
}

@keyframes rotation_9018 {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
/* From Uiverse.io by SouravBandyopadhyay */ 
.notification {
  display: flex;
  flex-direction: column;
  isolation: isolate;
  position: relative;
  width: 18rem;
  height: 8rem;
  background: var(--color-base-300);
  border-radius: 0rem;
  overflow: hidden;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-size: 16px;
  --gradient: linear-gradient(to bottom, #2eadff, #3d83ff, #7e61ff);
  --color: #32a6ff
}
/* 
.notification:before {
  position: absolute;
  content: "";
  inset: 0.0625rem;
  background: var(--color-base-200);
  z-index: 2
}

.notification:after {
  position: absolute;
  content: "";
  width: 0.25rem;
  inset: 0.65rem auto 0.65rem 0.5rem;
  background: var(--gradient);
  transition: transform 300ms ease;
  z-index: 4;
}
 */
.notification:hover:after {
  transform: translateX(0.15rem)
}

.notititle {
  color: var(--color);
  padding: 0.65rem 0.25rem 0.4rem 1.25rem;
  font-weight: 500;
  font-size: 1.6rem;
  transition: transform 300ms ease;
  z-index: 5;
}

.notification:hover .notititle {
  transform: translateX(0.15rem)
}

.notibody {
  padding: 0 1.25rem;
  transition: transform 300ms ease;
  z-index: 5;
}

.notification:hover .notibody {
  transform: translateX(0.25rem)
}

.notiglow,
.notiborderglow {
  position: absolute;
  width: 20rem;
  height: 20rem;
  transform: translate(-50%, -50%);
  background: radial-gradient(circle closest-side at center, white, transparent);
  opacity: 0;
  transition: opacity 300ms ease;
}

.notiglow {
  z-index: 3;
}

.notiborderglow {
  z-index: 1;
}

.notification:hover .notiglow {
  opacity: 0.1
}

.notification:hover .notiborderglow {
  opacity: 0.1
}

.note {
  color: var(--color);
  position: fixed;
  top: 80%;
  left: 50%;
  transform: translateX(-50%);
  text-align: center;
  font-size: 0.9rem;
  width: 75%;
}

 .menu-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(270px, 1fr));
            gap: 20px;
            max-width: 1200px;
            width: 100%;
        }

        .menu-card {
            background: var(--color-base-200);
            backdrop-filter: blur(10px);
/*             border-radius: 20px;
 */            padding: 30px 30px;
 
            min-width: none; 
            position: relative;
            overflow: hidden;
            cursor: pointer;
            transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            height: -webkit-fill-available;
            align-content: center;
        }

        .menu-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            opacity: 0;
            transition: opacity 0.4s ease;
            z-index: 0;
        }

        .menu-card:hover {
            transform: translateY(-10px) scale(1.02);
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }

        .menu-card:hover::before {
            opacity: 1;
        }

        .card-content {
            position: relative;
            z-index: 1;
            transition: color 0.4s ease;
        }

        .menu-card:hover .card-content
        {
            color: /*var(--color-primary)*/black;
        }

        .icon {
            font-size: 48px;
            margin-bottom: 20px;
            display: block;
            transition: transform 0.4s ease;
        }

        .menu-card:hover .icon {
            transform: scale(1.1) /*rotate(5deg)*/;
        }

        .title {
/*             font-family: 'Playfair Display', serif;
 */            font-size: 28px;
            font-weight: 700;
            margin-bottom: 12px;
            letter-spacing: -0.5px;
        }

        .description {
            font-size: 15px;
            line-height: 1.6;
            opacity: 0.8;
            font-weight: 400;
        }

        .menu-card:hover .description {
            opacity: 0.95;
        }

        .arrow {
            position: absolute;
            bottom: 20px;
            right: 20px;
            font-size: 24px;
            opacity: 0;
            transform: translateX(-10px);
            transition: all 0.4s ease;
        }

        .menu-card:hover .arrow {
            opacity: 1;
            transform: translateX(0);
        }

        /* Individual card colors */
        .card-1::before {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        }

        .card-2::before {
            background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        }

        .card-3::before {
            background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%);
        }

        .card-4::before {
            background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
        }

        .card-5::before {
            background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%);
        }

        .card-6::before {
            background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%);
        }

        .card-7::before {
            background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%);
        }

        .card-8::before {
            background: linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%);
        }

        .card-9::before {
            background: linear-gradient(135deg, #d299c2 0%, #fef9d7 100%);
        }

        @media (max-width: 768px) {
            .menu-container {
                grid-template-columns: 1fr;
            }
        }
</style>
