import type { NavRoutesMap } from "./MenuTypes";

/***
 * This object is used for generating main menu
 */

export const navRoutes: NavRoutesMap = 
{
    "/home": {
      label: "Početak",
      icon: "home",
      href: "#/home",
      component: "/home",
      admin: true,
      customer: false,
      default: true,
    },
    "/stats": {
      label: "Statistike",
      icon: "bar-chart",
      href: "#/stats",
      component: "/stats",
      admin: true,
      customer: false,
      default: false,
    },
    "/users": {
      label: "Korisnici",
      icon: "users",
      href: "#/users",
      component: "/users",
      componentDetails: "/users/:id",
      admin: true,
      customer: false,
    },
    "/products": {
      label: "Jelovnik",
      icon: "book",
      href: "#/products",
      component: "/products",
      componentDetails: "/products/:id",
      admin: true,
      customer: true,
      default: true,
    },
    "/products/mngmt": {
      label: "Upravljanje proizvodima",
      icon: "box",
      href: "#/products-mngmt",
      component: "/products-mngmt",
      componentDetails: "/products-mngmt/:id",
      admin: true,
      customer: false,
    },
    "/orders": {
      label: "Narudžbe",
      icon: "truck",
      href: "#/orders",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/cart": {
      label: "Košarica",
      icon: "shopping-basket",
      href: "#/cart",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/tables": {
      label: "Stolovi",
      icon: "table",
      href: "#/tables",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/reservations": {
      label: "Rezervacije",
      icon: "calendar",
      href: "#/reservations",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/checkout": {
      label: "Checkout",
      icon: "credit-card",
      href: "#/checkout",
      component: null,
      disabled: false,
      hidden: true,
      admin: true,
      customer: true,
    },   
    "/statistics": {
      label: "Statistics",
      icon: "bar-chart",
      href: "#/statistics",
      component: null,
      disabled: true,
      admin: false,
      customer: false,
    }, 
    "/pix": {
      label: "Galerija",
      icon: "image",
      href: "#/pix",
      component: null,
      disabled: false,
      hidden: false,
      admin: true,
      customer: false,
    },  
    "/logout": {
      label: "Logout",
      icon: "right-from-bracket",
      href: "#/logout",
      component: "Logout",
      disabled: false,
      hidden: false,
      admin: true,
      customer: false,
      default: true,
    },
  };