import type { NavRoutesMap } from "./MenuTypes";

/***
 * This object is used for generating main menu
 */

export const navRoutes: NavRoutesMap = 
{
    "/home": {
      label: "Home",
      icon: "home",
      href: "#/home",
      component: "/home",
      admin: true,
      customer: false,
      default: true,
    },
    "/users": {
      label: "Users",
      icon: "users",
      href: "#/users",
      component: "/users",
      componentDetails: "/users/:id",
      admin: true,
      customer: false,
    },
    "/products": {
      label: "Products",
      icon: "box",
      href: "#/products",
      component: "/products",
      componentDetails: "/products/:id",
      admin: true,
      customer: true,
    },
    "/products/mngmt/:id": {
      label: "Products administration",
      icon: "box",
      href: "#/products?listView=true",
      component: null,
      componentDetails: "/products/mngmt/:id",
      admin: true,
      customer: false,
    },
    "/orders": {
      label: "Orders",
      icon: "truck",
      href: "#/orders",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/cart": {
      label: "My cart",
      icon: "shopping-basket",
      href: "#/cart",
      component: null,
      disabled: false,
      admin: true,
      customer: true,
    },
    "/checkout": {
      label: "Checkout",
      icon: "credit-card",
      href: "#/checkout",
      component: null,
      disabled: false,
      hidden: true,
      admin: true,
      customer: true,
    },   
    "/statistics": {
      label: "Statistics",
      icon: "bar-chart",
      href: "#/statistics",
      component: null,
      disabled: true,
      admin: false,
      customer: false,
    }, 
    "/pix": {
      label: "Pictures",
      icon: "image",
      href: "#/pix",
      component: null,
      disabled: false,
      hidden: false,
      admin: true,
      customer: false,
    },  
    "/logout": {
      label: "Logout",
      icon: "right-from-bracket",
      href: "#/logout",
      component: "Logout",
      disabled: false,
      hidden: false,
      admin: true,
      customer: false,
      default: true,
    },
  };