<script lang="ts">
  import { onMount } from "svelte";
  import { getCurrentRole } from "./services/SessionStore";

  document.title = "Pegasus";

  type Item = {
    title: string;
    description: string;
    icon: string;
    href: string;
    color: string;
    admin: boolean;
    customer: boolean;
    default: boolean;
    id: number;
  };

  const allItems: Item[] = [
    {
      title: "👤 Korisnici",
      description: "Upravljanje korisnicima",
      icon: "users--",
      href: "/users",
      color: "blue",
      default: false,
      admin: true,
      customer: false,
      id: 0,
    },
    {
      title: "📓 Jelovnik",
      description: "Pregledaj proizvode",
      icon: "box--",
      href: "/products?listView=false",
      color: "green",
      default: true,
      admin: true,
      customer: true,
      id: 1,
    },
    {
      id: 2,
      title: "📚 Upravljanje proizvodima",
      description: "Manage store items",
      icon: "box--",
      href: "/products?listView=true",
      color: "yellow",
      default: false,
      admin: true,
      customer: false,
    },
    {
      id: 3,
      title: "🧺 Košarica",
      description: "Pregledaj proizvode u košarici",
      icon: "", //"shopping-basket",
      href: "/cart",
      color: "orange",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 4,
      title: "📝 Narudzbe",
      description: "View and manage orders",
      icon: "truck--",
      href: "/orders",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 5,
      title: "📅 Rezervacije",
      description: "Upravljaj rezervacijama",
      icon: "truck--",
      href: "/reservations",
      color: "red",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 6,
      title: "🪑 Stolovi ",
      description: "View and manage tables",
      icon: "--table",
      href: "/tables",
      color: "yellow",
      default: false,
      admin: true,
      customer: true,
    },
    {
      id: 7,
      title: "🖼️ Gallery",
      description:
        "View and manage picture gallery. Billions of free pictures, by Unsplash API",
      icon: "//image",
      href: "/pix",
      color: "violet",
      default: true,
      admin: true,
      customer: true,
    },
  ];

  const role = getCurrentRole();

  const getItemsByRole = (role: "ADMIN" | "CUSTOMER" | "EMPLOYEE"): Item[] => {
    return allItems.filter((route) => {
      if (route.default) return true;

      if (role === "ADMIN" || role === "EMPLOYEE") return route.admin === true;
      if (role === "CUSTOMER") return route.customer === true;

      return false;
    });
  };

  let items = getItemsByRole(role);

  async function addItemsWithDelay(
    sourceItems: Item[],
    addFn: (item: Item) => void,
    delay = 60
  ) {
    for (const item of sourceItems) {
      addFn(item);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }
  let displayedItems: Item[] = [];

  onMount(() => {
    addItemsWithDelay(
      items,
      (item) => (displayedItems = [...displayedItems, item])
    );
  });
</script>

<div
  class="max-w-7xl mx-auto px-6 py-10
  grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 scale-up-center-normal"
>
  {#each displayedItems as item}


    <a
      href="#{item.href}"
      class=""
    >
   <div class="notification">
    <div class="notiglow"></div>
    <div class="notiborderglow"></div>
    <div class="notititle">        {item.title}</div>
    <div class="notibody">        {item.description}</div>
  </div>
    </a>


  {/each}
</div>

<style>
  @keyframes wave {
    0%,
    100% {
      transform: translateX(0);
    }
    50% {
      transform: translateX(-50px);
    }
  }
  @keyframes slide {
    0% {
      transform: translateX(-20px) translateY(-20px);
    }
    100% {
      transform: translateX(20px) translateY(20px);
    }
  }

  @keyframes float {
    0%,
    100% {
      transform: translate(0, 0) scale(1);
    }
    33% {
      transform: translate(30px, -20px) scale(1.1);
    }
    66% {
      transform: translate(-20px, 30px) scale(0.9);
    }
  }
  /*********************************/
  /* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:00
* animation scale-up-center-normal
* ----------------------------------------
*/
  @keyframes scale-up-center-normal {
    0% {
      transform: scale(0.5);
    }
    100% {
      transform: scale(1);
    }
  }
  .scale-up-center-normal {
    animation: scale-up-center-normal 0.25s ease-out 0s 1 normal both;
  }
  .menu-block {
    display: inline-block; /* needed for transform to work properly */
    transition: transform 0.2s ease;
  }
  .menu-block:hover {
    transform: scale(2.1); /* 10% bigger */
  }
  .gblock {
    background-color: #003153 !important;
    background-image: linear-gradient(315deg, #062840 0%, #000 74%) !important;
  }

  /* From Uiverse.io by ElSombrero2 */ 
.card {
  width: 190px;
  height: 254px;
  background: #171717;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  position: relative;
  box-shadow: 0px 0px 3px 1px #00000088;
  cursor: pointer;
}

.card .content {
  border-radius: 5px;
  background: #171717;
  width: 186px;
  height: 250px;
  z-index: 1;
  padding: 20px;
  color: white;
  display: flex;
  justify-content: center;
  align-items: center;
}

.content::before {
  opacity: 0;
  transition: opacity 300ms;
  content: " ";
  display: block;
  background: white;
  width: 5px;
  height: 50px;
  position: absolute;
  filter: blur(50px);
  overflow: hidden;
}

.card:hover .content::before {
  opacity: 1;
}

.card::before {
  opacity: 0;
  content: " ";
  position: absolute;
  display: block;
  width: 80px;
  height: 360px;
  background: linear-gradient(#ff2288, #387ef0);
  transition: opacity 300ms;
  animation: rotation_9018 8000ms infinite linear;
  animation-play-state: paused;
}

.card:hover::before {
  opacity: 1;
  animation-play-state: running;
}

.card::after {
  position: absolute;
  content: " ";
  display: block;
  width: 250px;
  height: 360px;
  background: #17171733;
  backdrop-filter: blur(50px);
}

@keyframes rotation_9018 {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
/* From Uiverse.io by SouravBandyopadhyay */ 
.notification {
  display: flex;
  flex-direction: column;
  isolation: isolate;
  position: relative;
  width: 18rem;
  height: 8rem;
  background: #29292c;
  border-radius: 1rem;
  overflow: hidden;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
  font-size: 16px;
  --gradient: linear-gradient(to bottom, #2eadff, #3d83ff, #7e61ff);
  --color: #32a6ff
}

.notification:before {
  position: absolute;
  content: "";
  inset: 0.0625rem;
  border-radius: 0.9375rem;
  background: #18181b;
  z-index: 2
}

.notification:after {
  position: absolute;
  content: "";
  width: 0.25rem;
  inset: 0.65rem auto 0.65rem 0.5rem;
  border-radius: 0.125rem;
  background: var(--gradient);
  transition: transform 300ms ease;
  z-index: 4;
}

.notification:hover:after {
  transform: translateX(0.15rem)
}

.notititle {
  color: var(--color);
  padding: 0.65rem 0.25rem 0.4rem 1.25rem;
  font-weight: 500;
  font-size: 1.1rem;
  transition: transform 300ms ease;
  z-index: 5;
}

.notification:hover .notititle {
  transform: translateX(0.15rem)
}

.notibody {
  color: #99999d;
  padding: 0 1.25rem;
  transition: transform 300ms ease;
  z-index: 5;
}

.notification:hover .notibody {
  transform: translateX(0.25rem)
}

.notiglow,
.notiborderglow {
  position: absolute;
  width: 20rem;
  height: 20rem;
  transform: translate(-50%, -50%);
  background: radial-gradient(circle closest-side at center, white, transparent);
  opacity: 0;
  transition: opacity 300ms ease;
}

.notiglow {
  z-index: 3;
}

.notiborderglow {
  z-index: 1;
}

.notification:hover .notiglow {
  opacity: 0.1
}

.notification:hover .notiborderglow {
  opacity: 0.1
}

.note {
  color: var(--color);
  position: fixed;
  top: 80%;
  left: 50%;
  transform: translateX(-50%);
  text-align: center;
  font-size: 0.9rem;
  width: 75%;
}
</style>
