<script lang="ts">
  import { link } from "svelte-spa-router";
  import { navRoutes } from "./navRoutes";

  // Function to get navigation items (for menu display)
  function getNavigationItems() 
  {
    return Object.values(navRoutes).map((route) => ({
      label: route.label,
      icon: route.icon,
      href: route.href,
      inProgress: route.inProgress,
      tags: route.tags,
      disabled: route.disabled,
      hidden: !!route.hidden,
    }));
  }

  //This object is used for displaying menu
  const navItems = getNavigationItems();
</script>

<ul
  
  class="menu menu-sm dropdown-content bg-base-100 dark:bg-slate-800 rounded-box mt-3 w-52 p-2 shadow scale-in-ver-top"
>
  {#each navItems as item}
    <li>
      {#if !item.disabled}
        <a
          use:link
          href={item.disabled ? "#" : item.href}
          class="flex items-center px-3 py-2 rounded-md transition-colors text-base
                text-gray-700 dark:text-gray-200 
                hover:bg-gradient-to-r hover:from-[#0f172a]  hover:to-[#334155]
                hover:text-gray-400 
                cursor-pointer"
        >
          <i class="fas fa-{item.icon} w-5 mr-2"></i>
          <span>{item.label}</span>
        </a>
      {:else}
        <div
          class="flex items-center px-3 py-2 rounded-md transition-colors
                pointer-events-none text-gray-400 dark:text-gray-500
              hover:text-gray-400 dark:hover:text-gray-500 text-base"
        >
          <i class="fas fa-{item.icon} w-5 mr-2"></i>
          <span class="text-gray-400">{item.label}</span>
        </div>
      {/if}
    </li>
  {/each}
</ul>


<style>
  /* ----------------------------------------------

* Generated by Gradienty on 2025-06-02 15:58

* animation scale-up-ver-top-normal

* ----------------------------------------

*/

  @keyframes scale-up-ver-top {0% { transform: scaleY(0.4); transform-origin: 100% 0%; } 100% { transform: scaleY(1); transform-origin: 100% 0%;} }

.scale-up-ver-top-normal {
  animation: scale-up-ver-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0s 1 normal both;
}


/* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:09
* animation roll-in-top-normal
* ----------------------------------------
*/
  @keyframes roll-in-top {0% { transform: translateY(-800px) rotate(-540deg); opacity: 0; } 100% { transform: translateY(0) rotate(0deg); opacity: 1;} }

.roll-in-top-normal { 
    animation: roll-in-top 0.6s ease-out 0s 1 normal both; 
}

/* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:11
* animation scale-up-top-normal
* ----------------------------------------
*/
  @keyframes scale-up-top {0% { transform: scale(0.5); transform-origin: 50% 0%; } 100% { transform: scale(1); transform-origin: 50% 0%;} }

.scale-up-top-normal { 
    animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 0s 1 normal both; 
}


/* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:12
* animation scale-in-ver-top-normal
* ----------------------------------------
*/
  @keyframes scale-in-ver-top {0% { transform: scaleY(0); transform-origin: 100% 0%; opacity: 1; } 100% { transform: scaleY(1); transform-origin: 100% 0%; opacity: 1;} }

.scale-in-ver-top { 
    animation: scale-in-ver-top 0.15s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0s 1 normal both; 
}
/* ----------------------------------------------
* Generated by Gradienty on 2025-06-02 16:14
* animation scale-in-hor-left-normal
* ----------------------------------------
*/
  @keyframes scale-in-hor-left {0% { transform: scaleX(0); transform-origin: 0% 0%; opacity: 1; } 100% { transform: scaleX(1); transform-origin: 0% 0%; opacity: 1;} }

.scale-in-hor-left { 
    animation: scale-in-hor-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0s 1 normal both; 
}
</style>